'use client';

import { useEffect,useMemo,useRef,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import { CheckCircle2,Clock3,Scissors } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { trackMarketplaceEvent } from '@/lib/marketplace-telemetry';

type Service={id:string;name:string;description:string|null;duration_minutes:number;price_amount:number;currency:string};
type Slot={starts_at:string;available_professionals:number};

export default function BookingWizard(){
  const router=useRouter(); const search=useSearchParams(); const {user,hydrated}=useAuth();
  const type=search.get('type')||''; const provider=search.get('provider')||''; const startedRef=useRef(false);
  const [services,setServices]=useState<Service[]>([]); const [serviceId,setServiceId]=useState(search.get('service')||'');
  const [slots,setSlots]=useState<Slot[]>([]); const [start,setStart]=useState(search.get('start')||''); const [note,setNote]=useState('');
  const [loading,setLoading]=useState(true); const [slotsLoading,setSlotsLoading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!type||!provider){setError('Contexte de réservation invalide.');setLoading(false);return;}fetch(`/api/marketplace/booking/options?type=${encodeURIComponent(type)}&provider=${encodeURIComponent(provider)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Chargement impossible.');return d;}).then(d=>{setServices(d.services||[]);if(!serviceId&&d.services?.[0])setServiceId(d.services[0].id);if(!startedRef.current&&(type==='professional'||type==='salon')){startedRef.current=true;trackMarketplaceEvent({event:'booking_started',providerType:type,providerId:provider,source:'booking_wizard',properties:{servicePreselected:Boolean(serviceId)}});}}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[type,provider]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!serviceId)return;setSlotsLoading(true);setStart('');const from=new Date();const to=new Date(Date.now()+7*24*3600*1000);fetch(`/api/marketplace/booking/availability?service=${encodeURIComponent(serviceId)}&from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`).then(r=>r.json()).then(d=>setSlots(d.slots||[])).catch(()=>setSlots([])).finally(()=>setSlotsLoading(false));},[serviceId]);
  const selected=useMemo(()=>services.find(s=>s.id===serviceId)||null,[services,serviceId]);
  const confirm=async()=>{if(!selected||!start)return;setError(null);if(!hydrated)return;if(!user){const next=`/booking?type=${encodeURIComponent(type)}&provider=${encodeURIComponent(provider)}&service=${encodeURIComponent(serviceId)}&start=${encodeURIComponent(start)}&resume=1`;router.push(`/connexion?next=${encodeURIComponent(next)}`);return;}setSaving(true);try{const response=await fetch('/api/marketplace/booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serviceId,startsAt:start,note})});const d=await response.json();if(response.status===401){router.push(`/connexion?next=${encodeURIComponent(window.location.pathname+window.location.search)}`);return;}if(!response.ok)throw new Error(d.error||'Réservation impossible.');if(type==='professional'||type==='salon')trackMarketplaceEvent({event:'booking_created',providerType:type,providerId:provider,source:'booking_wizard',properties:{hasCustomerNote:Boolean(note.trim())}});router.push(`/workspace?context=personal&section=bookings&booking=${encodeURIComponent(d.bookingId)}`);}catch(e){setError(e instanceof Error?e.message:'Réservation impossible.');}finally{setSaving(false);}};
  if(loading)return <main className="min-h-screen bg-cream p-6"><div className="max-w-3xl mx-auto h-80 bg-card rounded-card animate-pulse"/></main>;
  return <main className="min-h-screen bg-cream text-ink px-4 sm:px-6 py-8"><div className="max-w-3xl mx-auto"><button onClick={()=>router.back()} className="text-sm font-bold text-ink-soft">← Retour</button><div className="mt-5"><p className="font-hand text-2xl text-terracotta">votre rendez-vous</p><h1 className="font-display text-4xl sm:text-5xl">Réserver en quelques étapes</h1><p className="mt-2 text-ink-soft">Le Try-On n’est pas obligatoire. Choisissez simplement votre prestation et un créneau.</p></div>
    {error&&<div className="mt-6 rounded-input border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <section className="mt-7 rounded-card bg-card border border-ink/10 p-5 sm:p-6"><div className="flex gap-3"><span className="w-9 h-9 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center font-bold">1</span><div className="flex-1"><h2 className="font-display text-2xl">Prestation</h2><div className="mt-4 space-y-2">{services.map(s=><label key={s.id} className={`block rounded-input border p-4 cursor-pointer ${serviceId===s.id?'border-terracotta bg-terracotta-wash':'border-ink/10'}`}><input type="radio" name="service" className="sr-only" checked={serviceId===s.id} onChange={()=>setServiceId(s.id)}/><div className="flex justify-between gap-4"><div><p className="font-bold">{s.name}</p><p className="text-xs text-ink-soft mt-1 inline-flex items-center gap-1"><Clock3 className="w-3.5 h-3.5"/>{s.duration_minutes} min</p></div><p className="font-display text-lg whitespace-nowrap">{Number(s.price_amount).toLocaleString('fr-FR')} {s.currency}</p></div></label>)}</div></div></div></section>
    <section className="mt-4 rounded-card bg-card border border-ink/10 p-5 sm:p-6"><div className="flex gap-3"><span className="w-9 h-9 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center font-bold">2</span><div className="flex-1 min-w-0"><h2 className="font-display text-2xl">Date & heure</h2><p className="text-sm text-ink-soft mt-1">Premier professionnel disponible lorsque vous réservez un salon.</p>{slotsLoading?<div className="mt-4 h-24 rounded-input bg-cream animate-pulse"/>:<div className="mt-4 grid grid-cols-2 sm:grid-cols-3 gap-2 max-h-64 overflow-y-auto">{slots.slice(0,30).map(slot=>{const d=new Date(slot.starts_at);return <button key={slot.starts_at} onClick={()=>setStart(slot.starts_at)} className={`rounded-input border p-3 text-left ${start===slot.starts_at?'border-terracotta bg-terracotta-wash':'border-ink/10'}`}><p className="text-xs text-ink-soft">{d.toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short'})}</p><p className="font-bold mt-1">{d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</p></button>})}{!slots.length&&!slotsLoading&&<p className="col-span-full text-sm text-ink-soft">Aucun créneau disponible sur les 7 prochains jours.</p>}</div>}</div></div></section>
    <section className="mt-4 rounded-card bg-card border border-ink/10 p-5 sm:p-6"><div className="flex gap-3"><span className="w-9 h-9 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center font-bold">3</span><div className="flex-1"><h2 className="font-display text-2xl">Confirmation</h2>{selected&&<div className="mt-4 rounded-input bg-cream p-4"><p className="font-bold">{selected.name}</p><p className="text-sm text-ink-soft mt-1">{start?new Date(start).toLocaleString('fr-FR',{dateStyle:'full',timeStyle:'short'}):'Choisissez un créneau'}</p><p className="mt-2 font-display text-xl">{Number(selected.price_amount).toLocaleString('fr-FR')} {selected.currency}</p><p className="mt-1 text-xs text-ink-soft">Paiement de la prestation directement auprès du professionnel pour le MVP.</p></div>}<label className="block mt-4 text-xs font-bold">Note facultative<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} className="mt-1.5 w-full min-h-24 rounded-input border border-ink/10 bg-cream p-3 font-normal" placeholder="Longueur, finition, précision utile…"/></label><button disabled={!start||!selected||saving} onClick={confirm} className="mt-5 min-h-[50px] w-full rounded-pill bg-terracotta text-white font-bold disabled:opacity-40 inline-flex items-center justify-center gap-2">{saving?<><Scissors className="w-4 h-4 animate-pulse"/>Confirmation…</>:<><CheckCircle2 className="w-5 h-5"/>{user?'Confirmer le rendez-vous':'Continuer pour confirmer'}</>}</button>{!user&&hydrated&&<p className="mt-2 text-xs text-center text-ink-soft">Vous pourrez choisir votre créneau avant de vous connecter.</p>}</div></div></section>
  </div></main>;
}
