'use client';

import { useEffect,useState } from 'react';
import Link from 'next/link';
import { CalendarDays,CheckCircle2,Clock3,MapPin,Scissors,Star,Users } from 'lucide-react';
import BackButton from '@/components/BackButton';
import { trackMarketplaceEvent } from '@/lib/marketplace-telemetry';

type ProviderType='professional'|'salon';
export default function PublicProviderProfile({type,slug}:{type:ProviderType;slug:string}){
  const [data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{fetch(`/api/marketplace/${type==='professional'?'professionals':'salons'}/${encodeURIComponent(slug)}`,{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Profil introuvable.');return b;}).then(b=>{setData(b);const entity=type==='professional'?b.profile:b.salon;if(entity?.id)trackMarketplaceEvent({event:'provider_view',providerType:type,providerId:entity.id,source:'public_profile',properties:{hasVerifiedReviews:Number(b.rating?.count||0)>0}});}).catch(e=>setError(e instanceof Error?e.message:'Profil introuvable.')).finally(()=>setLoading(false));},[type,slug]);
  if(loading)return <main className="min-h-screen bg-cream p-8"><div className="max-w-5xl mx-auto animate-pulse h-64 rounded-card bg-card border border-ink/10"/></main>;
  if(error||!data)return <main className="min-h-screen bg-cream text-ink flex items-center justify-center p-6"><div className="text-center"><h1 className="font-display text-3xl">Profil indisponible</h1><p className="text-ink-soft mt-2">{error}</p><Link href="/discover" className="inline-block mt-5 text-terracotta font-bold">Retour à la découverte</Link></div></main>;
  const isPro=type==='professional';const entity=isPro?data.profile:data.salon;const name=entity.name;const city=isPro?entity.city:entity.address?.city;const neighborhood=isPro?entity.neighborhood:entity.address?.neighborhood;const services=data.services??[];const rating=data.rating??{average:0,count:0};const reviews=data.reviews??[];
  const trackBooking=(source:string,serviceId?:string)=>trackMarketplaceEvent({event:'booking_started',providerType:type,providerId:entity.id,source,properties:{withService:Boolean(serviceId)}});
  return <main className="min-h-screen bg-cream text-ink pb-28 sm:pb-12">
    <section className="border-b border-ink/10 bg-card"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-12"><BackButton label="Découvrir" fallbackHref="/discover" /><div className="mt-6 flex flex-col sm:flex-row sm:items-end justify-between gap-5"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs rounded-pill px-3 py-1 bg-terracotta-wash text-terracotta font-bold">{isPro?'Professionnel indépendant':'Salon'}</span><span className="inline-flex items-center gap-1 text-xs font-bold text-terracotta"><CheckCircle2 className="w-4 h-4"/>Vérifié</span>{rating.count>0&&<span className="inline-flex items-center gap-1 text-xs font-bold"><Star className="w-4 h-4 text-terracotta fill-current"/>{rating.average.toFixed(1)} · {rating.count} avis vérifiés</span>}</div><h1 className="font-display text-4xl sm:text-5xl mt-3">{name}</h1><p className="text-ink-soft mt-2 max-w-2xl">{entity.headline||entity.description||'Découvrez les prestations et le savoir-faire sur Afrofade.'}</p>{(city||neighborhood)&&<p className="mt-3 inline-flex items-center gap-2 text-sm"><MapPin className="w-4 h-4 text-terracotta"/>{[neighborhood,city].filter(Boolean).join(' · ')}</p>}</div><Link onClick={()=>trackBooking('provider_profile_hero')} href={`/booking?type=${type}&provider=${encodeURIComponent(entity.id)}`} className="hidden sm:inline-flex min-h-[48px] px-6 rounded-pill bg-terracotta text-white font-bold items-center gap-2"><CalendarDays className="w-4 h-4"/>Réserver</Link></div></div></section>
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 grid lg:grid-cols-[1fr_320px] gap-8"><div className="space-y-9">
      <section><h2 className="font-display text-2xl">Prestations</h2><div className="mt-4 space-y-3">{services.length?services.map((s:any)=><div key={s.id} className="rounded-card bg-card border border-ink/10 p-5 flex justify-between gap-4"><div><h3 className="font-bold">{s.name}</h3><p className="text-sm text-ink-soft mt-1">{s.description||'Prestation disponible sur réservation.'}</p><p className="mt-2 text-xs inline-flex items-center gap-1 text-ink-soft"><Clock3 className="w-3.5 h-3.5"/>{s.duration_minutes} min</p></div><div className="text-right"><p className="font-display text-xl whitespace-nowrap">{Number(s.price_amount).toLocaleString('fr-FR')} {s.currency}</p><Link onClick={()=>trackBooking('provider_service_card',s.id)} href={`/booking?type=${type}&provider=${encodeURIComponent(entity.id)}&service=${encodeURIComponent(s.id)}`} className="mt-2 inline-flex text-xs font-bold text-terracotta">Réserver →</Link></div></div>):<p className="text-sm text-ink-soft">Les prestations seront bientôt publiées.</p>}</div></section>
      {isPro&&<section><h2 className="font-display text-2xl">Réalisations</h2><div className="mt-4 grid grid-cols-2 sm:grid-cols-3 gap-3">{(data.portfolio??[]).length?(data.portfolio??[]).map((item:any)=><div key={item.id} className="aspect-square rounded-card overflow-hidden border border-ink/10 bg-card">{item.imageUrl?<img src={item.imageUrl} alt={item.title||`Réalisation de ${name}`} className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center"><Scissors className="w-6 h-6 text-ink-soft"/></div>}</div>):<p className="col-span-full text-sm text-ink-soft">Portfolio en cours de publication.</p>}</div></section>}
      {!isPro&&<section><h2 className="font-display text-2xl">Notre équipe</h2><div className="mt-4 grid sm:grid-cols-2 gap-3">{(data.team??[]).length?(data.team??[]).map((m:any)=><Link key={m.id} href={m.slug?`/professionnels/${m.slug}`:'#'} className="rounded-card bg-card border border-ink/10 p-4"><div className="flex items-center gap-3"><span className="w-10 h-10 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center"><Users className="w-4 h-4"/></span><div><p className="font-bold">{m.professional_name}</p><p className="text-xs text-ink-soft">{m.headline||'Professionnel Afrofade'}</p></div></div></Link>):<p className="text-sm text-ink-soft">L’équipe sera bientôt visible.</p>}</div></section>}
      <section><div className="flex items-end justify-between gap-3"><div><h2 className="font-display text-2xl">Avis vérifiés</h2><p className="text-sm text-ink-soft mt-1">Uniquement liés à des prestations Afrofade terminées.</p></div>{rating.count>0&&<p className="font-display text-2xl">★ {rating.average.toFixed(1)}</p>}</div><div className="mt-4 grid sm:grid-cols-2 gap-3">{reviews.length?reviews.map((r:any)=><article key={r.id} className="rounded-card bg-card border border-ink/10 p-4"><p className="font-bold text-terracotta">{'★'.repeat(r.rating)}<span className="text-ink/15">{'★'.repeat(5-r.rating)}</span></p><p className="mt-2 text-sm">{r.comment||'Prestation évaluée sans commentaire.'}</p><p className="mt-3 text-xs text-ink-soft inline-flex items-center gap-1"><CheckCircle2 className="w-3.5 h-3.5 text-terracotta"/>Prestation vérifiée</p></article>):<p className="col-span-full text-sm text-ink-soft">Aucun avis vérifié pour le moment.</p>}</div></section>
    </div><aside className="lg:sticky lg:top-24 lg:self-start rounded-card bg-card border border-ink/10 p-5 shadow-soft"><p className="font-display text-2xl">Prêt à réserver ?</p><p className="text-sm text-ink-soft mt-2">Choisissez une prestation et un créneau disponible. Le Try-On reste optionnel.</p><Link onClick={()=>trackBooking('provider_profile_aside')} href={`/booking?type=${type}&provider=${encodeURIComponent(entity.id)}`} className="mt-5 w-full min-h-[48px] rounded-pill bg-terracotta text-white font-bold flex items-center justify-center gap-2"><CalendarDays className="w-4 h-4"/>Réserver</Link></aside></div>
    <div className="sm:hidden fixed bottom-0 left-0 right-0 bg-card border-t border-ink/10 p-3 pb-[calc(.75rem+env(safe-area-inset-bottom))] z-40"><Link onClick={()=>trackBooking('provider_profile_mobile')} href={`/booking?type=${type}&provider=${encodeURIComponent(entity.id)}`} className="min-h-[50px] rounded-pill bg-terracotta text-white font-bold flex items-center justify-center gap-2"><CalendarDays className="w-4 h-4"/>Réserver</Link></div>
  </main>;
}
