'use client';

import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
import { useRouter,useSearchParams } from 'next/navigation';
import { AlertTriangle,BriefcaseBusiness,CheckCircle2,EyeOff,Flag,RefreshCw,ShieldCheck,Star,XCircle } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { DashboardSkeleton } from '@/components/DashboardSkeleton';

type Tab='verification'|'reports'|'reviews'|'jobs';
type ModerationData={verification:any[];reports:any[];reviews:any[];audit:any[]};
const tabs:[Tab,string][]=[['verification','Vérifications'],['reports','Signalements'],['reviews','Avis'],['jobs','Offres Careers']];

export default function MarketplaceModerationConsole(){
 const router=useRouter(),search=useSearchParams(),{user,hydrated}=useAuth();const raw=search.get('tab');const tab:Tab=raw==='reports'||raw==='reviews'||raw==='jobs'?raw:'verification';
 const[data,setData]=useState<ModerationData|null>(null),[jobs,setJobs]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const load=async()=>{setLoading(true);setError(null);try{const[m,j]=await Promise.all([fetch('/api/admin/marketplace/moderation',{cache:'no-store'}),fetch('/api/admin/marketplace/jobs',{cache:'no-store'})]);const md=await m.json(),jd=await j.json();if(!m.ok)throw new Error(md.error||'Modération indisponible.');if(!j.ok)throw new Error(jd.error||'Offres indisponibles.');setData(md);setJobs(jd.jobs||[]);}catch(e){setError(e instanceof Error?e.message:'Chargement impossible.');}finally{setLoading(false);}};
 useEffect(()=>{if(!hydrated)return;if(!user){router.replace('/connexion?next=/admin/marketplace');return;}if(user.role!=='admin'){router.replace('/workspace');return;}void load();},[hydrated,user,router]); // eslint-disable-line react-hooks/exhaustive-deps
 const counts=useMemo(()=>({verification:data?.verification.length||0,reports:data?.reports.length||0,reviews:data?.reviews.length||0,jobs:jobs.length}),[data,jobs]);
 const moderate=async(kind:string,id:string,action:string)=>{setBusy(`${kind}:${id}:${action}`);setError(null);try{const url=kind==='job'?'/api/admin/marketplace/jobs':'/api/admin/marketplace/moderation';const body=kind==='job'?{jobId:id,action}:{kind,id,action};const r=await fetch(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Action impossible.');await load();}catch(e){setError(e instanceof Error?e.message:'Action impossible.');}finally{setBusy(null);}};
 if(!hydrated||!user||user.role!=='admin'||loading)return <DashboardSkeleton darkHeader/>;
 return <main className="min-h-screen bg-cream text-ink"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 sm:py-10"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><Link href="/admin" className="text-sm font-bold text-ink-soft">← Retour admin</Link><p className="font-hand text-2xl text-terracotta mt-3">trust & safety</p><h1 className="font-display text-4xl sm:text-5xl">Modération Marketplace</h1><p className="mt-2 text-ink-soft">Vérifications, signalements, avis et offres Careers dans une seule file de travail.</p></div><button onClick={()=>void load()} className="min-h-[44px] rounded-pill border border-ink/15 bg-card px-4 font-bold inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Actualiser</button></div>{error&&<div className="mt-5 rounded-input border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-7 flex gap-2 overflow-x-auto pb-1">{tabs.map(([value,label])=><button key={value} onClick={()=>router.replace(`/admin/marketplace?tab=${value}`)} className={`min-h-[42px] whitespace-nowrap rounded-pill px-4 border text-sm font-bold ${tab===value?'bg-ink text-white border-ink':'bg-card border-ink/10'}`}>{label} <span className="ml-1 opacity-70">{counts[value]}</span></button>)}</div><section className="mt-6 space-y-3">
 {tab==='verification'&&(data?.verification.length?data.verification.map(item=><article key={item.id} className="rounded-card bg-card border border-ink/10 p-5 shadow-soft"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.12em] text-terracotta font-bold">{item.entity_type==='professional'?'Professionnel':'Salon'}</p><h2 className="font-display text-2xl mt-1">{item.entity?.professional_name||item.entity?.name||'Entité Afrofade'}</h2><p className="text-xs text-ink-soft mt-2">Demande du {new Date(item.created_at).toLocaleString('fr-FR')}</p>{item.evidence&&Object.keys(item.evidence).length>0&&<pre className="mt-3 max-w-2xl overflow-auto rounded-input bg-cream p-3 text-[11px]">{JSON.stringify(item.evidence,null,2)}</pre>}</div><div className="flex gap-2"><button disabled={busy!==null} onClick={()=>moderate('verification',item.id,'approve')} className="min-h-[42px] rounded-pill bg-terracotta text-white px-4 font-bold inline-flex items-center gap-2"><ShieldCheck className="w-4 h-4"/>Valider</button><button disabled={busy!==null} onClick={()=>moderate('verification',item.id,'reject')} className="min-h-[42px] rounded-pill border border-ink/15 px-4 font-bold inline-flex items-center gap-2"><XCircle className="w-4 h-4"/>Refuser</button></div></div></article>):<Empty icon={ShieldCheck} text="Aucune vérification en attente."/>)}
 {tab==='reports'&&(data?.reports.length?data.reports.map(item=><article key={item.id} className="rounded-card bg-card border border-ink/10 p-5"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.12em] text-terracotta font-bold">{item.entity_type}</p><h2 className="font-bold mt-1">{item.reason}</h2><p className="text-sm text-ink-soft mt-2">{item.details||'Aucun détail supplémentaire.'}</p><p className="text-xs text-ink-soft mt-2">{new Date(item.created_at).toLocaleString('fr-FR')}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy!==null} onClick={()=>moderate('report',item.id,'review')} className="min-h-[40px] rounded-pill border border-ink/15 px-4 text-sm font-bold">Examiner</button><button disabled={busy!==null} onClick={()=>moderate('report',item.id,'resolve')} className="min-h-[40px] rounded-pill bg-terracotta text-white px-4 text-sm font-bold">Résoudre</button><button disabled={busy!==null} onClick={()=>moderate('report',item.id,'dismiss')} className="min-h-[40px] rounded-pill border border-ink/15 px-4 text-sm font-bold">Classer</button></div></div></article>):<Empty icon={Flag} text="Aucun signalement ouvert."/>)}
 {tab==='reviews'&&(data?.reviews.length?data.reviews.map(item=><article key={item.id} className="rounded-card bg-card border border-ink/10 p-5"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><p className="font-bold text-terracotta">{'★'.repeat(Number(item.rating||0))}</p><p className="mt-2 text-sm">{item.comment||'Avis sans commentaire.'}</p><p className="mt-2 text-xs text-ink-soft">Statut : {item.moderation_status}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy!==null} onClick={()=>moderate('review',item.id,'publish')} className="min-h-[40px] rounded-pill bg-terracotta text-white px-4 text-sm font-bold inline-flex items-center gap-1"><CheckCircle2 className="w-4 h-4"/>Publier</button><button disabled={busy!==null} onClick={()=>moderate('review',item.id,'hide')} className="min-h-[40px] rounded-pill border border-ink/15 px-4 text-sm font-bold inline-flex items-center gap-1"><EyeOff className="w-4 h-4"/>Masquer</button><button disabled={busy!==null} onClick={()=>moderate('review',item.id,'remove')} className="min-h-[40px] rounded-pill border border-red-200 text-red-700 px-4 text-sm font-bold">Retirer</button></div></div></article>):<Empty icon={Star} text="Aucun avis à modérer."/>)}
 {tab==='jobs'&&(jobs.length?jobs.map(job=><article key={job.id} className="rounded-card bg-card border border-ink/10 p-5"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.12em] text-terracotta font-bold">Offre Careers</p><h2 className="font-display text-2xl mt-1">{job.title}</h2><p className="text-sm font-bold mt-1">{Array.isArray(job.salons)?job.salons[0]?.name:job.salons?.name}</p><p className="mt-2 text-sm text-ink-soft line-clamp-3">{job.description}</p><p className="mt-2 text-xs text-ink-soft">{job.city||'Ville non précisée'} · {job.moderation_status}</p></div><div className="flex gap-2"><button disabled={busy!==null} onClick={()=>moderate('job',job.id,'approve')} className="min-h-[42px] rounded-pill bg-terracotta text-white px-4 font-bold">Valider</button><button disabled={busy!==null} onClick={()=>moderate('job',job.id,'reject')} className="min-h-[42px] rounded-pill border border-ink/15 px-4 font-bold">Refuser</button></div></div></article>):<Empty icon={BriefcaseBusiness} text="Aucune offre Careers à modérer."/>)}
 </section><section className="mt-10 rounded-card bg-card border border-ink/10 p-5"><h2 className="font-display text-2xl">Journal récent</h2><div className="mt-4 space-y-2">{(data?.audit||[]).slice(0,10).map(item=><div key={item.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 border-b border-ink/5 pb-2 text-xs"><span><strong>{item.action}</strong> · {item.entity_type}</span><span className="text-ink-soft">{new Date(item.created_at).toLocaleString('fr-FR')}</span></div>)}{!data?.audit?.length&&<p className="text-sm text-ink-soft">Aucune action récente.</p>}</div></section></div></main>;
}

function Empty({icon:Icon,text}:{icon:typeof AlertTriangle;text:string}){return <div className="rounded-card bg-card border border-ink/10 p-8 text-center"><Icon className="w-7 h-7 text-terracotta mx-auto"/><p className="font-display text-2xl mt-3">{text}</p></div>}
