import { NextRequest,NextResponse } from 'next/server';
import { getVerifiedPrincipal } from '@/lib/server-auth';
import { getServiceSupabase } from '@/lib/supabase';

function clean(v:unknown,max:number){return typeof v==='string'?v.trim().slice(0,max):'';}
export async function GET(req:NextRequest){
  try{const db=getServiceSupabase();const city=clean(req.nextUrl.searchParams.get('city'),120);const skill=clean(req.nextUrl.searchParams.get('skill'),100);let q=db.from('job_postings').select('id,salon_id,title,description,city,neighborhood,work_mode,experience_min_years,compensation_min,compensation_max,currency,deadline,created_at,salons(id,slug,name),job_posting_skills(required,hair_taxonomy(id,slug,label_fr))').eq('status','published').eq('moderation_status','approved').order('created_at',{ascending:false}).limit(50);if(city)q=q.ilike('city',city);const{data,error}=await q;if(error)throw error;let jobs=data||[];if(skill)jobs=jobs.filter((j:any)=>(j.job_posting_skills||[]).some((s:any)=>s.hair_taxonomy?.slug===skill));return NextResponse.json({jobs});}catch(error){console.error('[Careers Jobs GET]',error);return NextResponse.json({error:'Impossible de charger les offres.'},{status:500});}
}
export async function POST(req:NextRequest){
  try{const principal=await getVerifiedPrincipal(req);if(!principal)return NextResponse.json({error:'Authentification requise.'},{status:401});const body=await req.json();const salonId=clean(body?.salonId,64),title=clean(body?.title,180),description=clean(body?.description,8000),city=clean(body?.city,120),neighborhood=clean(body?.neighborhood,160),workMode=['onsite','mobile','hybrid'].includes(body?.workMode)?body.workMode:'onsite';const experience=Math.max(0,Math.min(50,Number(body?.experienceMinYears||0)));const skills=Array.isArray(body?.taxonomyIds)?body.taxonomyIds.filter((x:unknown)=>typeof x==='string').slice(0,20):[];if(!salonId||!title||!description)return NextResponse.json({error:'Salon, titre et description sont requis.'},{status:400});const db=getServiceSupabase();const{data:membership,error:mError}=await db.from('salon_memberships').select('role').eq('salon_id',salonId).eq('user_id',principal.user.id).eq('status','active').in('role',['owner','manager']).maybeSingle();if(mError)throw mError;if(!membership)return NextResponse.json({error:'Vous ne pouvez pas publier pour ce salon.'},{status:403});const{data:job,error}=await db.from('job_postings').insert({salon_id:salonId,created_by:principal.user.id,title,description,city:city||null,neighborhood:neighborhood||null,work_mode:workMode,experience_min_years:experience,compensation_min:Number.isFinite(Number(body?.compensationMin))?Number(body.compensationMin):null,compensation_max:Number.isFinite(Number(body?.compensationMax))?Number(body.compensationMax):null,currency:'XOF',status:'draft',moderation_status:'pending',deadline:body?.deadline&&Date.parse(body.deadline)?new Date(body.deadline).toISOString():null}).select('id,status,moderation_status').single();if(error||!job)throw error||new Error('job_create_failed');if(skills.length){const{error:sError}=await db.from('job_posting_skills').insert(skills.map((taxonomy_id:string)=>({job_posting_id:job.id,taxonomy_id,required:true})));if(sError)throw sError;}return NextResponse.json({job,message:'Offre créée en brouillon. Soumettez-la à validation avant publication.'},{status:201});}catch(error){console.error('[Careers Jobs POST]',error);return NextResponse.json({error:'Impossible de créer cette offre.'},{status:500});}
}
