'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, BriefcaseBusiness, Building2, CalendarDays, CheckCircle2, MapPin, Search, ShieldCheck, Sparkles, Star, UserRound } from 'lucide-react';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { RituelDemoVideo } from '@/components/RituelDemoVideo';

const categories = [
  ['Barber & Fades','barber-fades','Dégradés, contours et coupes barber'],
  ['Tresses','braids','Braids, cornrows et styles protecteurs'],
  ['Locks & Locs','locks-locs','Locks, retwist et entretien'],
  ['Afro & Twists','afro-twists','Afro, twists et textures naturelles'],
  ['Coiffure','hair-styling','Styles, finitions et occasions'],
  ['Barbe','beard','Contours, taille et barbe sculptée'],
];
const styleCards = [
  ['Knotless Braids','knotless-braids','Tresses'], ['Low Taper Fade','low-taper-fade','Barber & Fades'],
  ['Locks courtes','short-locks','Locks & Locs'], ['Cornrows','cornrows','Tresses'],
];
const faq = [
  ['Afrofade est-il gratuit pour les particuliers ?','La découverte des styles, professionnels et salons est accessible sans abonnement. Les fonctions IA/3D peuvent utiliser des crédits.'],
  ['Dois-je utiliser le Try-On pour réserver ?','Non. Vous pouvez rechercher un professionnel et réserver directement. Le Try-On est une option pour mieux visualiser votre choix.'],
  ['Puis-je trouver un professionnel indépendant ?','Oui. Afrofade référence des professionnels indépendants ainsi que des salons, selon leur disponibilité et leur éligibilité marketplace.'],
  ['Comment fonctionne la localisation ?','Vous pouvez saisir une ville ou utiliser votre position pour une recherche ponctuelle. La position GPS utilisée pour rechercher n’est pas enregistrée dans votre profil.'],
  ['Comment fonctionnent les avis vérifiés ?','Les avis vérifiés seront liés aux rendez-vous Afrofade réellement terminés afin de distinguer une expérience authentifiée d’un simple témoignage.'],
  ['Comment fonctionne l’essayage de coiffure ?','Afrofade Try-On vous permet de visualiser des styles sur vous puis d’utiliser le look choisi comme référence pour trouver un professionnel et, à terme, l’attacher à votre réservation.'],
];

export default function HomePage() {
  const router=useRouter(); const [q,setQ]=useState(''); const [city,setCity]=useState('Ouagadougou');
  const submit=(e:FormEvent)=>{e.preventDefault();const p=new URLSearchParams();if(q.trim())p.set('q',q.trim());if(city.trim())p.set('city',city.trim());router.push(`/discover?${p}`);};
  return <div className="min-h-screen bg-cream text-ink font-body">
    <main>
      <section className="max-w-container mx-auto px-4 sm:px-6 py-12 md:py-20 grid lg:grid-cols-[1.15fr_.85fr] gap-10 items-center">
        <div><p className="font-hand text-2xl text-terracotta">La coiffure commence avant le fauteuil ✦</p><h1 className="font-display text-[42px] sm:text-[54px] lg:text-[64px] leading-[1.04] mt-3">Trouvez le professionnel qui saura vraiment réaliser <span className="text-terracotta">votre style.</span></h1><p className="mt-5 text-base sm:text-lg text-ink-soft max-w-2xl">Découvrez des coiffures, essayez-les sur vous avec Afrofade, trouvez les salons et professionnels adaptés près de chez vous, puis réservez votre prestation.</p>
          <form onSubmit={submit} className="mt-8 bg-card border border-ink/10 rounded-card shadow-soft p-3 grid md:grid-cols-[1fr_240px_auto] gap-2"><label className="relative"><Search className="absolute left-4 top-4 w-5 h-5 text-ink-soft"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tresses, locks, taper fade…" className="w-full min-h-[52px] rounded-input bg-cream border border-ink/10 pl-12 pr-4"/></label><label className="relative"><MapPin className="absolute left-4 top-4 w-5 h-5 text-ink-soft"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ville ou quartier" className="w-full min-h-[52px] rounded-input bg-cream border border-ink/10 pl-12 pr-4"/></label><button className="min-h-[52px] rounded-pill bg-terracotta text-white font-bold px-6">Rechercher</button></form>
          <div className="mt-4 flex flex-wrap gap-2">{['Tresses','Fades','Locks','Afro','Barbe'].map(label=><Link key={label} href={`/discover?q=${encodeURIComponent(label)}&city=${encodeURIComponent(city)}`} className="rounded-pill border border-ink/10 bg-card px-4 py-2 text-sm font-bold hover:border-terracotta">{label}</Link>)}</div>
          <div className="mt-6 flex flex-wrap gap-5 text-sm font-bold"><Link href="/styles" className="text-terracotta">Explorer les styles →</Link><Link href="/rituel" className="text-terracotta">Essayer une coiffure sur moi →</Link></div>
        </div>
        <div className="rounded-card bg-night text-white p-6 sm:p-8 shadow-soft relative overflow-hidden"><div className="absolute -right-16 -top-16 w-52 h-52 rounded-full bg-terracotta/25"/><p className="text-xs tracking-[.14em] uppercase font-bold text-white/50">Style du moment</p><h2 className="font-display text-4xl mt-2">Knotless Braids</h2><p className="mt-2 text-white/65">Tresses protectrices · style essayable avec Afrofade</p><div className="mt-8 space-y-3">{[['Aïcha Hair','Ouaga 2000 · 1,6 km'],['Mariam Braids','Karpala · 3,2 km']].map(([name,place])=><div key={name} className="rounded-card border border-white/10 bg-white/5 p-4 flex items-center gap-3"><span className="w-10 h-10 rounded-full bg-terracotta flex items-center justify-center"><UserRound className="w-5 h-5"/></span><div className="min-w-0"><p className="font-bold">{name}</p><p className="text-xs text-white/55">{place}</p></div><span className="ml-auto text-sm text-terracotta font-bold">★ 4.9</span></div>)}</div><Link href="/discover?style=knotless-braids&city=Ouagadougou" className="mt-6 min-h-[48px] rounded-pill bg-white text-ink font-bold flex items-center justify-center">Voir les professionnels</Link></div>
      </section>

      <section className="max-w-container mx-auto px-4 sm:px-6 py-14"><p className="font-hand text-2xl text-terracotta">commencez simplement</p><h2 className="font-display text-3xl sm:text-4xl mt-1">Qu’est-ce que vous cherchez aujourd’hui ?</h2><div className="mt-7 grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{categories.map(([label,slug,desc])=><Link key={slug} href={`/discover?q=${encodeURIComponent(label)}&city=Ouagadougou`} className="group rounded-card bg-card border border-ink/10 p-5 shadow-soft hover:border-terracotta"><span className="w-11 h-11 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center"><Sparkles className="w-5 h-5"/></span><h3 className="font-display text-2xl mt-4">{label}</h3><p className="mt-1 text-sm text-ink-soft">{desc}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-terracotta">Découvrir <ArrowRight className="w-4 h-4"/></span></Link>)}</div></section>

      <section id="styles" className="bg-card py-14 md:py-20"><div className="max-w-container mx-auto px-4 sm:px-6"><p className="font-hand text-2xl text-terracotta">inspirez-vous</p><h2 className="font-display text-3xl sm:text-4xl mt-1">Trouvez le style qui vous ressemble</h2><p className="mt-2 text-ink-soft">Explorez, essayez si vous le souhaitez, puis trouvez qui peut réellement le réaliser.</p><div className="mt-7 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{styleCards.map(([name,slug,cat])=><article key={slug} className="rounded-card bg-cream border border-ink/10 overflow-hidden"><div className="h-40 bg-gradient-to-br from-terracotta-wash to-terracotta-pale flex items-center justify-center"><Sparkles className="w-9 h-9 text-terracotta"/></div><div className="p-4"><p className="text-xs text-ink-soft font-bold uppercase tracking-[.1em]">{cat}</p><h3 className="font-display text-xl mt-1">{name}</h3><div className="mt-4 flex gap-3 text-sm font-bold"><Link href={`/discover?style=${slug}&city=Ouagadougou`} className="text-terracotta">Trouver un pro</Link><Link href={`/rituel?style=${slug}`} className="text-ink-soft">Essayer</Link></div></div></article>)}</div><Link href="/styles" className="mt-7 inline-flex min-h-[46px] items-center rounded-pill border border-ink/15 px-5 font-bold">Explorer tous les styles</Link></div></section>

      <section className="max-w-container mx-auto px-4 sm:px-6 py-14 md:py-20"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="font-hand text-2xl text-terracotta">près de chez vous</p><h2 className="font-display text-3xl sm:text-4xl mt-1">Trouvez le bon talent</h2><p className="mt-2 text-ink-soft">Les résultats réels apparaissent dans Discover selon le style, la ville, l’éligibilité et bientôt la disponibilité et la réputation vérifiée.</p></div><Link href="/discover" className="font-bold text-terracotta">Voir tous les résultats →</Link></div><div className="mt-7 grid md:grid-cols-3 gap-4">{[['Professionnels','Compétences, portfolio et prestations','/discover?type=professional'],['Salons','Équipes, services et localisation','/discover?type=salon'],['Votre style','Cherchez directement qui peut le réaliser','/styles']].map(([title,text,href],i)=><Link key={title} href={href} className="rounded-card bg-card border border-ink/10 p-6 shadow-soft"><span className="w-11 h-11 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center">{i===1?<Building2 className="w-5 h-5"/>:i===0?<UserRound className="w-5 h-5"/>:<Sparkles className="w-5 h-5"/>}</span><h3 className="font-display text-2xl mt-4">{title}</h3><p className="mt-2 text-sm text-ink-soft">{text}</p></Link>)}</div></section>

      <section id="comment-ca-marche" className="bg-night text-white py-14 md:py-20"><div className="max-w-container mx-auto px-4 sm:px-6"><p className="font-hand text-2xl text-terracotta">de l’idée au rendez-vous</p><h2 className="font-display text-3xl sm:text-4xl mt-1">Simplement.</h2><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['01','Découvrez','Styles, salons et professionnels.'],['02','Essayez','Visualisez votre coiffure sur vous — optionnel.'],['03','Trouvez','Identifiez le talent adapté au résultat voulu.'],['04','Réservez','Choisissez la prestation et le créneau disponible.']].map(([n,t,d])=><div key={n} className="rounded-card border border-white/10 bg-white/5 p-5"><p className="font-display text-4xl text-terracotta">{n}</p><h3 className="font-bold mt-4">{t}</h3><p className="mt-2 text-sm text-white/60">{d}</p></div>)}</div></div></section>

      <section id="try-on" className="max-w-container mx-auto px-4 sm:px-6 py-14 md:py-20 grid lg:grid-cols-2 gap-10 items-center"><div><p className="text-xs uppercase tracking-[.15em] font-bold text-terracotta">AFROFADE TRY-ON</p><h2 className="font-display text-4xl sm:text-5xl mt-2">Voyez la coupe avant le premier coup de tondeuse.</h2><p className="mt-4 text-ink-soft">Essayez différents styles sur vous, comparez-les et transformez votre look préféré en référence pour trouver le professionnel adapté.</p><ul className="mt-6 space-y-3 text-sm">{['Essayez plusieurs styles','Visualisez différents angles','Enregistrez votre look','Utilisez-le comme référence pour votre réservation'].map(x=><li key={x} className="flex gap-2"><CheckCircle2 className="w-5 h-5 text-terracotta shrink-0"/>{x}</li>)}</ul><div className="mt-7 flex flex-wrap gap-3"><Link href="/rituel" className="min-h-[48px] rounded-pill bg-terracotta text-white px-6 font-bold flex items-center">Essayer une coiffure</Link><Link href="/rituel" className="min-h-[48px] rounded-pill border border-ink/15 px-6 font-bold flex items-center">Voir comment ça marche</Link></div></div><div className="rounded-card bg-card border border-ink/10 p-4 shadow-soft"><RituelDemoVideo/></div></section>

      <section className="bg-card py-14 md:py-20"><div className="max-w-container mx-auto px-4 sm:px-6"><p className="font-hand text-2xl text-terracotta">pour les professionnels</p><h2 className="font-display text-3xl sm:text-4xl mt-1">Faites grandir votre activité avec Afrofade</h2><p className="mt-2 text-ink-soft max-w-2xl">Présentez votre savoir-faire, recevez de nouveaux clients et gérez votre activité depuis un seul compte.</p><div className="mt-7 grid md:grid-cols-3 gap-4">{[['Professionnel indépendant','Portfolio · visibilité · réservations'],['Salon','Équipe · prestations · planning'],['Multi-salon','Établissements · gestion centralisée']].map(([t,d],i)=><div key={t} className="rounded-card bg-cream border border-ink/10 p-6"><span className="w-11 h-11 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center">{i===0?<UserRound className="w-5 h-5"/>:<Building2 className="w-5 h-5"/>}</span><h3 className="font-display text-2xl mt-4">{t}</h3><p className="mt-2 text-sm text-ink-soft">{d}</p></div>)}</div><div className="mt-7 flex gap-3 flex-wrap"><Link href="/pour-les-pros" className="min-h-[46px] rounded-pill bg-ink text-white px-5 font-bold flex items-center">Découvrir Afrofade Pro</Link><Link href="/pro/onboarding" className="min-h-[46px] rounded-pill border border-ink/15 px-5 font-bold flex items-center">Créer mon activité</Link></div></div></section>

      <section className="max-w-container mx-auto px-4 sm:px-6 py-14"><div className="grid lg:grid-cols-2 gap-8"><div><p className="font-hand text-2xl text-terracotta">choisissez en confiance</p><h2 className="font-display text-3xl sm:text-4xl">Le savoir-faire doit être visible.</h2><div className="mt-6 space-y-4">{[['Portfolio réel','Voyez les réalisations avant de choisir.'],['Avis vérifiés','Les prestations terminées pourront alimenter une réputation vérifiée.'],['Expertise visible','Styles, services et expérience structurés par taxonomie.']].map(([t,d],i)=><div key={t} className="flex gap-3"><span className="w-10 h-10 rounded-full bg-terracotta-wash text-terracotta flex items-center justify-center shrink-0">{i===1?<Star className="w-5 h-5"/>:<ShieldCheck className="w-5 h-5"/>}</span><div><h3 className="font-bold">{t}</h3><p className="text-sm text-ink-soft mt-1">{d}</p></div></div>)}</div></div><div className="rounded-card bg-night text-white p-7"><BriefcaseBusiness className="w-8 h-8 text-terracotta"/><h3 className="font-display text-3xl mt-4">Votre prochain talent est peut-être déjà sur Afrofade.</h3><p className="mt-3 text-white/60">Professionnels et salons pourront se rencontrer autour d’opportunités réellement liées aux métiers de la coiffure.</p><Link href="/careers" className="mt-6 inline-flex min-h-[46px] rounded-pill bg-white text-ink px-5 font-bold items-center">Explorer les carrières</Link></div></div></section>

      <section id="offres" className="bg-card py-14"><div className="max-w-container mx-auto px-4 sm:px-6"><h2 className="font-display text-3xl sm:text-4xl">Une formule adaptée à votre usage</h2><div className="mt-7 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Particulier','Marketplace gratuite · Try-On via crédits','/discover'],['Professionnel','Visibilité et activité indépendante','/pour-les-pros'],['Salon','Équipe, services et réservations','/pour-les-pros'],['Business','Multi-établissements','/pour-les-pros']].map(([t,d,h])=><Link key={t} href={h} className="rounded-card bg-cream border border-ink/10 p-5"><h3 className="font-display text-2xl">{t}</h3><p className="mt-2 text-sm text-ink-soft">{d}</p><span className="mt-5 inline-flex text-sm font-bold text-terracotta">En savoir plus →</span></Link>)}</div></div></section>

      <section id="faq" className="max-w-container mx-auto px-4 sm:px-6 py-14 md:py-20"><h2 className="font-display text-3xl sm:text-4xl">Questions fréquentes</h2><div className="mt-7 grid lg:grid-cols-2 gap-3">{faq.map(([q,a])=><details key={q} className="rounded-card bg-card border border-ink/10 p-5 group"><summary className="font-bold cursor-pointer list-none">{q}</summary><p className="mt-3 text-sm leading-relaxed text-ink-soft">{a}</p></details>)}</div></section>
    </main><Footer/>
  </div>;
}
