'use client';

import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, RefreshCw, Search } from 'lucide-react';
import { DashboardSkeleton } from '@/components/DashboardSkeleton';
import { useAuth } from '@/lib/auth';
import { formatFcfa } from '@/lib/plans';

const TITLES:Record<string,string>={salons:'Salons inscrits',subscriptions:'Abonnements',users:'Utilisateurs',revenue:'Chiffre d’affaires'};
function date(value:any){return value?new Date(String(value)).toLocaleString('fr-FR'):'—';}
function money(value:any){return `${formatFcfa(Number(value||0))} FCFA`;}

export default function AdminSectionPage(){const params=useParams<{section:string}>();const section=String(params.section||'');const router=useRouter();const{user,hydrated}=useAuth();const[data,setData]=useState<{items:Array<Record<string,any>>;summary?:Record<string,any>}|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[query,setQuery]=useState('');
const load=async()=>{setLoading(true);setError(null);try{const response=await fetch(`/api/admin/details/${section}`,{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Chargement impossible.');setData(payload);}catch(loadError){setError(loadError instanceof Error?loadError.message:'Chargement impossible.');}finally{setLoading(false);}};
useEffect(()=>{if(!hydrated)return;if(!user){router.replace(`/connexion?next=/admin/${section}`);return;}if(user.needsOnboarding){router.replace('/onboarding');return;}if(user.role!=='admin'){router.replace(user.role==='salon'?'/dashboard':'/account');return;}void load();},[hydrated,user,section,router]); // eslint-disable-line react-hooks/exhaustive-deps
const items=useMemo(()=>{const source=data?.items||[];const needle=query.trim().toLowerCase();return needle?source.filter((item)=>JSON.stringify(item).toLowerCase().includes(needle)):source;},[data,query]);
if(!hydrated||!user||user.role!=='admin'||loading)return <DashboardSkeleton darkHeader/>;
const renderRow=(item:Record<string,any>)=>{if(section==='salons')return <tr key={item.id} className="border-b border-ink/5"><td className="py-3 font-bold">{item.name}</td><td>{item.owner_email||'—'}</td><td>{item.country}</td><td>{item.plan}</td><td>{item.quota_used}/{item.quota_limit}</td><td>{item.subscription?`${item.subscription.provider} · actif`:'Sans abonnement'}</td><td>{date(item.created_at)}</td></tr>;if(section==='subscriptions')return <tr key={item.id} className="border-b border-ink/5"><td className="py-3 font-bold">{item.salon?.name||item.salon_id}</td><td>{item.provider}</td><td>{money(item.amount_fcfa)}</td><td>{item.status}</td><td>{date(item.expires_at)}</td><td>{date(item.created_at)}</td></tr>;if(section==='users')return <tr key={item.user_id} className="border-b border-ink/5"><td className="py-3 font-bold">{item.name||'—'}</td><td>{item.email||'—'}</td><td>{item.role}</td><td className="font-mono text-[10px]">{item.salon_id||'—'}</td><td>{date(item.last_sign_in_at)}</td><td>{date(item.created_at)}</td></tr>;return <tr key={item.id} className="border-b border-ink/5"><td className="py-3 font-bold">{item.provider}</td><td>{item.purpose}</td><td>{item.product_id}</td><td>{money(item.amount_fcfa)}</td><td>{item.currency}</td><td>{date(item.paid_at||item.created_at)}</td></tr>;};
const headers=section==='salons'?['Salon','Propriétaire','Pays','Plan','Quota','Abonnement','Inscription']:section==='subscriptions'?['Salon','Prestataire','Montant','Statut','Expiration','Création']:section==='users'?['Nom','Email','Rôle','Salon ID','Dernière connexion','Création']:['Prestataire','Type','Produit','Montant','Devise','Encaissé le'];
return <main className="min-h-screen bg-cream text-ink"><div className="max-w-container mx-auto px-6 py-10 space-y-6"><div className="flex items-center justify-between gap-4 flex-wrap"><div><Link href="/admin" className="text-xs font-bold text-terracotta inline-flex items-center gap-1"><ArrowLeft className="w-3.5 h-3.5"/>Retour admin</Link><h1 className="font-display text-3xl mt-2">{TITLES[section]||'Détail admin'}</h1><p className="text-sm text-ink-soft mt-1">{data?.items.length??0} enregistrement(s) chargé(s).</p></div><button onClick={()=>void load()} className="min-h-[44px] px-4 rounded-pill border border-ink/15 bg-card font-bold text-sm inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Actualiser</button></div>{error&&<div className="rounded-input border border-red-200 bg-red-50 text-red-700 px-4 py-3 text-sm">{error}</div>}{section==='revenue'&&data?.summary&&<div className="grid sm:grid-cols-2 gap-4"><div className="bg-card rounded-card border border-ink/10 p-5"><p className="text-xs text-ink-soft">CA encaissé</p><p className="font-display text-2xl mt-1">{money(data.summary.totalRevenueFcfa)}</p></div><div className="bg-card rounded-card border border-ink/10 p-5"><p className="text-xs text-ink-soft">Transactions payées</p><p className="font-display text-2xl mt-1">{data.summary.paidTransactions}</p></div></div>}<div className="relative max-w-md"><Search className="absolute left-3 top-3.5 w-4 h-4 text-ink-soft"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Rechercher dans cette vue…" className="w-full min-h-[44px] rounded-pill border border-ink/15 bg-card pl-10 pr-4 text-sm"/></div><section className="bg-card rounded-card border border-ink/10 shadow-soft overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="bg-ink/[.03] border-b border-ink/10 text-[10px] uppercase tracking-[.1em] text-ink-soft">{headers.map((header)=><th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{items.length?items.map(renderRow):<tr><td colSpan={headers.length} className="p-8 text-center text-ink-soft">Aucun résultat.</td></tr>}</tbody></table></div></section></div></main>;
}
