'use client';

import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
import { BriefcaseBusiness,ChevronRight,Plus,Scissors,Users } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { DashboardSkeleton } from '@/components/DashboardSkeleton';

type Ctx={key:string;type:string;id:string|null;label:string;role:string};
type Job={id:string;title:string;status:string;moderation_status:string;city:string|null;created_at:string};
type App={id:string;status:string;profile_snapshot:any;submitted_at:string;professional_profiles:any;job_postings:any};
const nextByStatus:Record<string,string[]>={submitted:['viewed','shortlisted','rejected'],viewed:['shortlisted','rejected'],shortlisted:['interview','rejected'],interview:['offered','rejected'],offered:['hired','rejected']};
export default function CareersManager(){
 const{user,hydrated}=useAuth();const[contexts,setContexts]=useState<Ctx[]>([]),[salonId,setSalonId]=useState(''),[jobs,setJobs]=useState<Job[]>([]),[apps,setApps]=useState<App[]>([]),[taxonomy,setTaxonomy]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[invite,setInvite]=useState<string|null>(null);const[form,setForm]=useState({title:'',description:'',city:'Ouagadougou',workMode:'onsite',experienceMinYears:0,taxonomyIds:[] as string[]});
 useEffect(()=>{if(!hydrated)return;if(!user){window.location.assign('/connexion?next=/careers/manage');return;}Promise.all([fetch('/api/workspace/contexts').then(r=>r.json()),fetch('/api/marketplace/taxonomy').then(r=>r.json())]).then(([c,t])=>{const salons=(c.contexts||[]).filter((x:Ctx)=>x.type==='salon'&&['owner','manager'].includes(x.role));setContexts(salons);if(salons[0])setSalonId(salons[0].id);setTaxonomy((t.taxonomy||[]).filter((x:any)=>x.kind==='style'||x.kind==='skill'));}).catch(()=>setError('Impossible de charger votre contexte.'));},[hydrated,user]);
 const load=async(id:string)=>{if(!id)return;setError(null);try{const[j,a]=await Promise.all([fetch(`/api/careers/manage?salon=${encodeURIComponent(id)}`).then(r=>r.json()),fetch(`/api/careers/applications?salon=${encodeURIComponent(id)}`).then(r=>r.json())]);setJobs(j.jobs||[]);setApps(a.applications||[]);}catch{setError('Impossible de charger le recrutement.');}};
 useEffect(()=>{void load(salonId);},[salonId]);
 const createJob=async()=>{if(!salonId||!form.title||!form.description)return;setBusy(true);setError(null);try{const r=await fetch('/api/careers/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({salonId,...form})});const d=await r.json();if(!r.ok)throw new Error(d.error);setForm(v=>({...v,title:'',description:'',taxonomyIds:[]}));await load(salonId);}catch(e){setError(e instanceof Error?e.message:'Création impossible.');}finally{setBusy(false);}};
 const transition=async(id:string,status:string)=>{setBusy(true);try{const r=await fetch('/api/careers/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId:id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(salonId);}catch(e){setError(e instanceof Error?e.message:'Transition impossible.');}finally{setBusy(false);}};
 const createInvite=async(id:string)=>{setBusy(true);try{const r=await fetch('/api/careers/hire-invitation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setInvite(`${window.location.origin}${d.acceptPath}`);}catch(e){setError(e instanceof Error?e.message:'Invitation impossible.');}finally{setBusy(false);}};
 const salonLabel=useMemo(()=>contexts.find(c=>c.id===salonId)?.label||'Salon',[contexts,salonId]);
 if(!hydrated||!user)return <DashboardSkeleton/>;
 return <main className="min-h-screen bg-cream text-ink px-4 sm:px-6 py-8"><div className="max-w-6xl mx-auto"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><Link href="/workspace" className="text-sm font-bold text-ink-soft">← Workspace</Link><p className="font-hand text-2xl text-terracotta mt-3">recrutement</p><h1 className="font-display text-4xl">Trouver votre prochain talent</h1></div><select value={salonId} onChange={e=>setSalonId(e.target.value)} className="min-h-[46px] rounded-pill border border-ink/15 bg-card px-4 font-bold">{contexts.map(c=><option key={c.key} value={c.id||''}>{c.label}</option>)}</select></div>{error&&<div className="mt-5 rounded-input border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{invite&&<div className="mt-5 rounded-card bg-terracotta-wash border border-terracotta/20 p-4"><p className="font-bold">Invitation prête</p><p className="text-sm mt-1 break-all">{invite}</p><p className="text-xs text-ink-soft mt-2">Envoyez ce lien au candidat. Son accès ne sera créé qu’après acceptation.</p></div>}
 <div className="mt-7 grid lg:grid-cols-[360px_1fr] gap-6"><section className="rounded-card bg-card border border-ink/10 p-5 h-fit"><div className="flex items-center gap-2"><Plus className="w-5 h-5 text-terracotta"/><h2 className="font-display text-2xl">Nouvelle offre</h2></div><p className="text-xs text-ink-soft mt-1">{salonLabel} · soumise à modération avant publication.</p><div className="mt-4 space-y-3"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex. Tresseuse / Braider" className="w-full min-h-[46px] rounded-input border border-ink/10 bg-cream px-3"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Mission, attentes, organisation…" className="w-full min-h-32 rounded-input border border-ink/10 bg-cream p-3"/><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Ville" className="w-full min-h-[46px] rounded-input border border-ink/10 bg-cream px-3"/><select value={form.workMode} onChange={e=>setForm({...form,workMode:e.target.value})} className="w-full min-h-[46px] rounded-input border border-ink/10 bg-cream px-3"><option value="onsite">Sur place</option><option value="mobile">Mobile</option><option value="hybrid">Hybride</option></select><div className="flex flex-wrap gap-2 max-h-36 overflow-y-auto">{taxonomy.slice(0,24).map((t:any)=>{const on=form.taxonomyIds.includes(t.id);return <button key={t.id} type="button" onClick={()=>setForm(v=>({...v,taxonomyIds:on?v.taxonomyIds.filter(x=>x!==t.id):[...v.taxonomyIds,t.id]}))} className={`rounded-pill px-3 py-1.5 text-xs font-bold border ${on?'bg-terracotta text-white border-terracotta':'border-ink/10'}`}>{t.label_fr}</button>})}</div><button onClick={createJob} disabled={busy||!salonId} className="w-full min-h-[46px] rounded-pill bg-terracotta text-white font-bold disabled:opacity-40">Créer le brouillon</button></div><div className="mt-6 border-t border-ink/10 pt-4"><p className="text-xs font-bold uppercase text-ink-soft">Mes offres</p><div className="mt-2 space-y-2">{jobs.map(j=><div key={j.id} className="rounded-input bg-cream p-3"><p className="font-bold text-sm">{j.title}</p><p className="text-xs text-ink-soft mt-1">{j.status} · modération {j.moderation_status}</p></div>)}</div></div></section>
 <section><div className="flex items-center gap-2"><Users className="w-5 h-5 text-terracotta"/><h2 className="font-display text-2xl">Candidatures</h2></div><div className="mt-4 space-y-3">{apps.length?apps.map(a=>{const p=Array.isArray(a.professional_profiles)?a.professional_profiles[0]:a.professional_profiles;const j=Array.isArray(a.job_postings)?a.job_postings[0]:a.job_postings;return <article key={a.id} className="rounded-card bg-card border border-ink/10 p-5"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.1em] font-bold text-terracotta">{j?.title}</p><h3 className="font-display text-2xl mt-1">{p?.professional_name||a.profile_snapshot?.professionalName||'Professionnel'}</h3><p className="text-sm text-ink-soft mt-1">{p?.headline||a.profile_snapshot?.headline}</p></div><span className="rounded-pill bg-cream border border-ink/10 px-3 py-1 text-xs font-bold">{a.status}</span></div><div className="mt-4 flex flex-wrap gap-2">{(a.profile_snapshot?.skills||[]).slice(0,8).map((s:any)=><span key={s.slug} className="rounded-pill bg-terracotta-wash text-terracotta px-3 py-1 text-xs">{s.label}</span>)}</div><div className="mt-5 flex flex-wrap gap-2">{(nextByStatus[a.status]||[]).map(status=><button key={status} disabled={busy} onClick={()=>transition(a.id,status)} className="min-h-[40px] rounded-pill border border-ink/15 px-4 text-xs font-bold hover:border-terracotta">{status}<ChevronRight className="inline w-3 h-3 ml-1"/></button>)}{a.status==='hired'&&<button onClick={()=>createInvite(a.id)} disabled={busy} className="min-h-[40px] rounded-pill bg-ink text-white px-4 text-xs font-bold inline-flex items-center gap-2"><Scissors className="w-4 h-4"/>Inviter dans l’équipe</button>}</div></article>}):<div className="rounded-card bg-card border border-ink/10 p-8 text-center"><BriefcaseBusiness className="w-8 h-8 text-terracotta mx-auto"/><p className="font-display text-2xl mt-3">Pas encore de candidature.</p></div>}</div></section></div></div></main>;
}
